# Generated by Django 4.1.10 on 2023-10-14 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineName', models.CharField(max_length=50)),
                ('machinePrice', models.IntegerField()),
                ('machineDescription', models.CharField(max_length=50000)),
                ('machineNegotiatable', models.BooleanField(default=False)),
                ('machineImage', models.ImageField(upload_to='images/')),
                ('user', models.CharField(default='admin', max_length=1000)),
                ('dt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
