# Generated by Django 4.1.10 on 2023-10-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='machine',
            name='machineBrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.machinebrand'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machineCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.machinecategory'),
        ),
    ]
