# Generated by Django 4.1.10 on 2023-10-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_machine_machineprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandImage', models.ImageField(upload_to='brand/')),
                ('brandName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.machinebrand')),
            ],
        ),
    ]
