# Generated by Django 4.1.10 on 2023-10-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_brandimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machinePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
